- id: fmt
  name: fmt
  description: Format files with cargo fmt.
  entry: cargo fmt
  language: system
  types_or: ["rust", "file"]
  files: "(.rs|Cargo.toml)$"
  args: ["--"]
  stages:
    - pre-commit
    - pre-merge-commit
- id: cargo-check
  name: cargo check
  description: Check the package for errors.
  entry: cargo check
  language: system
  types_or: ["rust", "file"]
  files: "(.rs|Cargo.toml|Cargo.lock)$"
  stages:
    - pre-commit
    - pre-merge-commit
  pass_filenames: false
- id: clippy
  name: clippy
  description: Lint rust sources
  entry: cargo clippy
  language: system
  args: ["--", "-D", "warnings"]
  types: [rust]
  stages:
    - pre-commit
    - pre-merge-commit
  pass_filenames: false
- id: test
  name: test
  description: Run tests with cargo test
  entry: cargo test
  language: system
  types: [rust]
  args: ["--"]
  stages:
    - pre-push
    - manual
- id: build
  name: build
  description: Build using cargo build
  language: system
  types: ["rust"]
  stages:
    - pre-push
    - manual
  entry: cargo build
  pass_filenames: false
